theme: jekyll-theme-merlot
title: Tuan Nguyen
description: Fullstack Developer (NodeJS + ReactJS)
show_links: true
nodeplusplus:
  blog_url: https://blog.nodeplusplus.com/
  linkedin_url: https://www.linkedin.com/in/tuannguyen1993/
