theme: jekyll-theme-merlot
title: Web Developer
description: NodeJS & ReactJS
show_links: true
nodeplusplus:
  blog_url: https://blog.nodeplusplus.com/
  linkedin_url: https://www.linkedin.com/in/tuannguyen1993/
